[package]
name = "bellamy"
version = "0.1.0-alpha"
edition = "2021"
description = "Open URL in chromeless window"

[dependencies]
wry = "0.27.0"
clap = { version = "4.1.8", features = ["derive"] }

[build-dependencies]
winres = "0.1"

[profile.release]
strip = "symbols"
