[package]
name = "bellamy"
version = "1.0.0"
edition = "2021"
description = "Open URL in chromeless window"

[dependencies]
wry = "0.27.0"
clap = { version = "4.1.8", features = ["derive"] }

[profile.release]
strip = "symbols"
